services:
  dictionary-db:
    image: helboi4/japanese-dict-db:latest
    container_name: japanese-dict-db
    ports:
      - "5234:5432"
    volumes:
      - ./dictionary_db/init-readonly-user.sql:/docker-entrypoint-initdb.d/98-readonly-user.sql
      - ./dictionary_db/setup-pg-hba.sh:/docker-entrypoint-initdb.d/99-setup-pg-hba.sh
    restart: unless-stopped
    env_file:
      - ./dictionary_db/.env
